---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@0059c984cd57bb3a6d875be8d86690aa39780afd # v1.29.0
    permissions:
      contents: read
      packages: read
      statuses: write
